package persistence.sql.ddl;


import domain.Person;
import org.junit.jupiter.api.Test;
import persistence.sql.ddl.h2.H2CreateDdlBuilder;

import static org.assertj.core.api.Assertions.assertThat;

class CreateDdlBuilderTest {

    @Test
    void create_table_build() {
        CreateDdlBuilder createDdlBuilder = new H2CreateDdlBuilder();

        String actual = createDdlBuilder.createTableBuild(Person.class);

        assertThat(actual).isEqualTo("create table person (id bigint generated by default as identity, nick_name varchar(255), old integer, email varchar(255) not null, primary key (id))");
    }

}
