package persistence.sql.dialect.h2;

import jakarta.persistence.GenerationType;
import persistence.sql.dialect.Dialect;

import java.sql.Types;

public class H2Dialect extends Dialect {

    public H2Dialect() {
        registerColumnType(Types.BIGINT, "bigint");
        registerColumnType(Types.INTEGER, "integer");
        registerColumnType(Types.VARCHAR, "varchar(255)");
    }

    @Override
    public String generatorCreatePrimaryDdl(final GenerationType generationType) {
        if (GenerationType.IDENTITY == generationType) {
            return "generated by default as identity";
        }

        return "not null";
    }

    @Override
    public String getNotNullConstraint(boolean nullable) {
        if (nullable) {
            return "";
        }

        return "not null";
    }
}
