package persistence.dialect;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertAll;

class DatabaseTest {

    @Test
    void h2() {
        Database database = Database.H2;

        Dialect dialect = database.createDialect();

        assertAll(
                () -> assertThat(dialect.getNativeIdentifierGeneratorStrategy()).isEqualTo(" generated by default as identity"),
                () -> assertThat(dialect.columnType(SqlTypes.BIGINT)).isEqualTo("bigint"),
                () -> assertThat(dialect.columnType(SqlTypes.VARCHAR)).isEqualTo("varchar($l)"),
                () -> assertThat(dialect.columnType(SqlTypes.INTEGER)).isEqualTo("integer"),
                () -> assertThat(dialect.castColumnType("varchar($l)", 255L)).isEqualTo("varchar(255)")
        );
    }

}
