package persistence.dialect;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class H2IdentifyColumnDialectTest {

    @Test
    void identifyString() {
        H2IdentifyColumnDialect h2IdentifyColumnDialect = new H2IdentifyColumnDialect();

        assertThat(h2IdentifyColumnDialect.identifyColumnString()).isEqualTo(" generated by default as identity");
    }

}
