package persistence.dialect;

public class H2IdentifyColumnDialect implements IdentifyColumnDialect {
    @Override
    public String identifyColumnString() {
        return " generated by default as identity";
    }
}
