package persistence.entity;

import database.DatabaseServer;
import database.H2;
import entity.Person;
import jdbc.JdbcTemplate;
import org.junit.jupiter.api.*;
import persistence.sql.Query;
import persistence.sql.dialect.h2.H2Dialect;

import static org.assertj.core.api.Assertions.assertThat;

class SimpleEntityManagerTest {


    private static DatabaseServer server;
    private static JdbcTemplate jdbcTemplate;
    private static final Query query = new Query(new H2Dialect());
    private EntityManager entityManager;

    @BeforeAll
    static void beforeAll() throws Exception {
        try {
            server = new H2();
            server.start();
            jdbcTemplate = new JdbcTemplate(server.getConnection());
        } catch (Exception e) {
            throw new Exception(e);
        }
    }

    @AfterAll
    static void afterAll() {
        server.stop();
    }

    @BeforeEach
    void beforeEach() {
        jdbcTemplate.execute("create table users (id bigint generated by default as identity, nick_name varchar(255), old integer, email varchar(255) not null, primary key (id))");
        jdbcTemplate.execute("insert into users (id, nick_name, old, email) values (default, 'test1', 10, 'test1@gmail.com')");
        entityManager = new SimpleEntityManager(
                new EntityPersister(query, jdbcTemplate),
                new EntityLoader(query, jdbcTemplate),
                new SimplePersistenceContext()
        );
    }

    @AfterEach
    void afterEach() {
        jdbcTemplate.execute("drop table if exists users CASCADE");
    }

    @DisplayName("EntityManger#find를 통해 Entity를 조회한다.")
    @Test
    void findTest() {
        // given
        Person expected = new Person(1L, "test1", 10, "test1@gmail.com", 0);

        // when
        Person actual = entityManager.find(Person.class, 1L);

        // then
        assertThat(actual).isEqualTo(expected);
    }

    @DisplayName("EntityManger#persist를 통해 Entity를 신규 저장한다.")
    @Test
    void persistTest() {
        // given
        Person testEntity = new Person(2L, "test2", 11, "test2@gmail.com", 0);

        // when
        entityManager.persist(testEntity);
        Person found = entityManager.find(Person.class, 2L);

        // then
        assertThat(found).isEqualTo(testEntity);
    }

    @DisplayName("EntityManger#persist를 통해 Entity를 수정한다.")
    @Test
    void updateTest() {
        // given
        Person testEntity = new Person(1L, "test2", 11, "test2@gmail.com", 0);

        // when
        entityManager.persist(testEntity);
        Person found = entityManager.find(Person.class, 1L);

        // then
        assertThat(found).isEqualTo(testEntity);
    }

    @DisplayName("EntityManger#remove를 통해 Entity를 삭제한다.")
    @Test
    void removeTest() {
        // given
        Person testEntity = new Person(1L, "test1", 10, "test1@gmail.com", 0);

        // when
        entityManager.remove(testEntity);

        // then
        assertThat(entityManager.find(Person.class, 1L)).isNull();
    }

}
