package persistence.sql.ddl.h2;

import jakarta.persistence.GenerationType;
import persistence.entity.metadata.EntityColumn;
import persistence.sql.ddl.DDLQueryGenerator;
import persistence.sql.h2.H2Dialect;

public class H2DDLQueryGenerator extends DDLQueryGenerator {
    public H2DDLQueryGenerator() {
        super.dialect = new H2Dialect();
    }

    @Override
    protected String getColumnClause(EntityColumn entityColumn) {
        StringBuilder columnClause = new StringBuilder();

        String nullable = getNullable(entityColumn);
        String columnProperty = getColumnGenerator(entityColumn);
        String PK = getPrimaryKey(entityColumn);

        columnClause.append(entityColumn.getName());
        columnClause.append(" ");
        columnClause.append(getColumnDataType(entityColumn));
        columnClause.append(" ");
        if (columnProperty != null && !columnProperty.isEmpty()) {
            columnClause.append(columnProperty);
            columnClause.append(" ");
        }
        if (PK != null && !PK.isEmpty()) {
            columnClause.append(PK);
            columnClause.append(" ");
        }
        if (nullable != null && !nullable.isEmpty()) {
            columnClause.append(nullable);
            columnClause.append(" ");
        }

        return columnClause.toString();
    }

    private String getPrimaryKey(EntityColumn entityColumn) {
        if (entityColumn.isPrimaryKey()) {
            return "PRIMARY KEY";
        }
        return "";
    }
    private String getNullable(EntityColumn entityColumn) {
        return entityColumn.isNullable() ? "" : "NOT NULL";
    }
    private String getColumnGenerator(EntityColumn entityColumn) {
        if (entityColumn.isDataAutoGenerated()) {
            if (entityColumn.isPrimaryKey() && entityColumn.getGenerationType() == GenerationType.IDENTITY) {
                return "AUTO_INCREMENT";
            }
        }
        return "";
    }

    // TODO refactor this method
    private String getColumnDataType(EntityColumn entityColumn) {
        String columnType = dialect.getDataType(entityColumn.getSqlTypeCode());

        if ("VARCHAR".equals(columnType)) {
            int length = entityColumn.getLength();

            if (length == 0) {
                length = 255;
            }
            return columnType + "(" + length + ")";
        }

        return columnType;
    }
}
