package persistence.core;

import jdbc.JdbcTemplate;
import persistence.entity.metadata.EntityColumn;
import persistence.entity.metadata.EntityMetadata;
import persistence.sql.dml.DMLQueryBuilder;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class DefaultEntityPersister implements EntityPersister {
    private final JdbcTemplate jdbcTemplate;
    private final EntityMetaManager entityMetaManager;
    private final DMLQueryBuilder dmlQueryBuilder;

    public DefaultEntityPersister(JdbcTemplate jdbcTemplate) throws SQLException {
        this.jdbcTemplate = jdbcTemplate;
        this.entityMetaManager = EntityMetaManager.getInstance();
        this.dmlQueryBuilder = DMLQueryBuilder.getInstance();
    }

    @Override
    public Long insert(Object entity) {
        EntityMetadata entityMetadata = entityMetaManager.getEntityMetadata(entity.getClass());
        List<EntityColumn> columns = entityMetadata.getColumns().getColumns().stream().filter(column -> !column.isDataAutoGenerated()).collect(Collectors.toList());
        String sql = dmlQueryBuilder.insertSql(entityMetadata.getTableName(), columns, entityMetadata.getColumnValues(entity));
        return (Long) jdbcTemplate.execute(sql);
    }

    @Override
    public boolean update(Object entity) throws Exception {
        String sql = dmlQueryBuilder.updateSql(entity);
        jdbcTemplate.execute(sql);

        return true;
    }

    @Override
    public void delete(Object entity) throws Exception {
        String sql = dmlQueryBuilder.deleteSql(entity);
        jdbcTemplate.execute(sql);
    }

    @Override
    public void setIdentifier(Object entity, Object id) throws Exception {
        EntityDataManipulator.setIdValue(entity, id);
    }

}
