package persistence.entity.metadata;

import persistence.core.EntityContextManager;

import java.util.List;
import java.util.stream.Collectors;

public class DefaultEntityMetadataReader implements EntityMetadataReader {

    @Override
    public String getTableName(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getEntityTable().getTableName();
    }

    @Override
    public String getIdColumnName(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getIdColumn().getColumnName();
    }

    @Override
    public List<EntityColumn> getInsertTargetColumns(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getColumns()
                .stream()
                .filter(column -> !column.isDataAutoGenerated())
                .collect(Collectors.toList());
    }

    @Override
    public EntityColumn getEntityColumnByColumnName(Class<?> clazz, String columnName) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getColumnByColumnName(columnName);
    }

    @Override
    public List<EntityColumn> getColumns(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getColumns();
    }
}
