package persistence.entity.metadata;

import persistence.core.EntityContextManager;

import java.util.List;
import java.util.stream.Collectors;

public class DefaultEntityMetadataReader {

    public static String getTableName(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getEntityTable().getTableName();
    }

    public static String getIdColumnName(Class<?> clazz) {
        return getIdColumn(clazz).getColumnName();
    }

    public static EntityColumn getIdColumn(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getIdColumn();
    }

    public static List<EntityColumn> getInsertTargetColumns(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getColumns()
                .stream()
                .filter(column -> !column.isDataAutoGenerated())
                .collect(Collectors.toList());
    }


    public static EntityColumn getEntityColumnByColumnName(Class<?> clazz, String columnName) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getColumnByColumnName(columnName);
    }

    public static List<EntityColumn> getColumns(Class<?> clazz) {
        return EntityContextManager.getEntityMetadata(clazz).getColumns().getColumns();
    }
}
