package persistence.entity.metadata;

import jakarta.persistence.GenerationType;

public class EntityColumn {
    private String name;
    private int sqlTypeCode;
    private boolean isPrimaryKey;
    private boolean isNullable;
    private GenerationType generationType;
    private int length;

    public boolean isDataAutoGenerated() {
        return isPrimaryKey && generationType != null;
    }

    public String getName() {
        return name;
    }

    public int getSqlTypeCode() {
        return sqlTypeCode;
    }

    public boolean isPrimaryKey() {
        return isPrimaryKey;
    }

    public boolean isNullable() {
        return isNullable;
    }

    public GenerationType getGenerationType() {
        return generationType;
    }

    public int getLength() {
        return length;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setSqlTypeCode(int sqlTypeCode) {
        this.sqlTypeCode = sqlTypeCode;
    }

    public void setPrimaryKey(boolean primaryKey) {
        isPrimaryKey = primaryKey;
    }

    public void setNullable(boolean nullable) {
        isNullable = nullable;
    }

    public void setGenerationType(GenerationType generationType) {
        this.generationType = generationType;
    }

    public void setLength(int length) {
        this.length = length;
    }

    @Override
    public String toString() {
        return "EntityColumn{" +
            "name='" + name + '\'' +
            ", sqlTypeCode=" + sqlTypeCode +
            ", isPrimaryKey=" + isPrimaryKey +
            ", isNullable=" + isNullable +
            ", generationType=" + generationType +
            ", length=" + length +
            '}';
    }
}
