package persistence.entity.metadata;

import java.util.List;
import java.util.stream.Collectors;

public class EntityColumns {
    private List<EntityColumn> columns;

    public EntityColumns(List<EntityColumn> columns) {
        this.columns = columns;
    }

    public List<EntityColumn> getColumns() {
        return columns;
    }

    public void setColumns(List<EntityColumn> columns) {
        this.columns = columns;
    }

    public EntityColumn getIdColumn() {
        return columns.stream()
                .filter(EntityColumn::isPrimaryKey)
                .findFirst().orElse(null);
    }

    public List<EntityColumn> getInsertTargetColumns() {
        return columns.stream()
                .filter(column -> !column.isDataAutoGenerated())
                .collect(Collectors.toList());
    }



}
